# Generated by Django 3.1.5 on 2021-01-17 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210116_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Description',
            field=models.TextField(blank=True),
        ),
    ]
