# Generated by Django 3.1.5 on 2021-01-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_products_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
    ]
