# Generated by Django 3.1.5 on 2021-01-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210120_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Weight',
            field=models.DecimalField(decimal_places=2, default=5.99, max_digits=5),
        ),
    ]
